Action: Add Selected object
3liz/qgis-veloroutes_voies_vertes-plugin pull request #73
Opened 2020-10-08 15:06 UTC by drillinP

## Description

* Ticket : #66 and #67
*

2020-10-08 15:11 UTC, drillinP commented on veloroutes_voies_vertes/actions.py
> +        rel_layer.addFeatures([feat])
@mdouchin  ou @Gustry  J'ai un problème lors de l'ajout de la feature à ma couche. Je récupère les fields de ma couche que j'ajoute à ma nouvelle feature. Ensuite je renseigne les valeurs de deux champs. Quand je teste sur qgis dans ma table etape les valeurs sont en décalées et donc pas dans les bons champs.

2020-10-08 15:26 UTC, rldhont requested changes
Un 4 en 1 bravo. Concernant le `triggerRepaint` il faudrait avoir accès à la couche de l'action.

2020-10-08 15:26 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    print(match_list)
```suggestion
```
No print

2020-10-08 15:26 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +        _add_selected_from_relation(int(args[0]), 'id_itineraire', 'v_portion', 'id_portion', 'etape')
Il faudrait ajouter un `triggerRepaint` de la couche `v_itineraire`

2020-10-08 15:26 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +        _add_selected_from_relation(int(args[0]), 'id_portion', 'segment', 'id_segment', 'element')
Il faudrait ajouter un `triggerRepaint` de la couche `v_portion`

2020-10-08 15:40 UTC, drillinP commented
il faudra mettre à jour les qml ?

2020-10-08 16:25 UTC, rldhont requested changes

2020-10-08 16:25 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +        layers = QgsProject.instance().mapLayersByName('v_itineraire')
```suggestion
        layers = QgsProject.instance().mapLayersByName('v_portion')
```

2020-10-08 16:25 UTC, rldhont commented
> il faudra mettre à jour les qml ?

Oui il faudra les mettres à jour.

2020-10-09 07:10 UTC, rldhont requested changes

2020-10-09 07:10 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    if args[2] == 'del':
Je créerais des varaibles :
`layer_name` et `action`

2020-10-09 07:10 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    layers = QgsProject.instance().mapLayersByName('v_itineraire')
Utiliser `layer_name` ici

2020-10-09 07:10 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +            'v_itineraire'))
Utilisé `layer_name`

2020-10-09 07:10 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    layers = QgsProject.instance().mapLayersByName('v_itineraire')
Il faudrait même commencer par ça.

2020-10-09 07:18 UTC, Gustry approved these changes
Good move !

2020-10-09 07:18 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +    id_value = agg_id
Soit il faut renommer l'argument dans la fonction, soit renommer la variable ci-dessous.
Cette ligne ne sert à rien IMHO. Faire de même dans `_remove_selected_from_relation`

2020-10-09 07:18 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +        rel_layer.addFeatures([feat])
Utiliser `addFeature`

2020-10-09 07:18 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +    msg = "{} objet(s) ont été ajouté(s) de la couche {}".format(count, rel_layer_name)
```suggestion
    msg = "{} objet(s) ont été ajouté(s) de la couche {}".format(len(match_list), rel_layer_name)
```
et supprimer la variable `count`?

2020-10-09 07:33 UTC, rldhont approved these changes

2020-10-09 07:33 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    layer_name = args[1]
```suggestion
def update_selected_feature(*args):
    agg_id = int(args[0])
    layer_name = args[1]
```

2020-10-09 07:33 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +            _add_selected_from_relation(int(args[0]), 'id_portion', 'segment', 'id_segment', 'element')
```suggestion
    if action == 'del':
        if layer_name == 'v_itineraire':
            _remove_selected_from_relation(agg_id, 'id_itineraire', 'v_portion', 'id_portion', 'etape')
        if layer_name == 'v_portion':
            _remove_selected_from_relation(agg_id, 'id_portion', 'segment', 'id_segment', 'element')
    elif action == 'add':
        if layer_name == 'v_itineraire':
            _add_selected_from_relation(agg_id, 'id_itineraire', 'v_portion', 'id_portion', 'etape')
        elif layer_name == 'v_portion':
            _add_selected_from_relation(agg_id, 'id_portion', 'segment', 'id_segment', 'element')
```

2020-10-09 07:42 UTC, merged