Action: add features from selected features
3liz/qgis-veloroutes_voies_vertes-plugin pull request #74
Opened 2020-10-09 15:03 UTC by drillinP

## Description

* Ticket : #64 and #65
*

2020-10-12 08:11 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    update_layer.commitChanges()
```suggestion
    update_layer.committedFeaturesAdded.connect(partial(_add_relation, selected_features_id))
    update_layer.commitChanges()
    update_layer.committedFeaturesAdded.disconnect(partial(_add_relation, selected_features_id))
```
Faire la déconnection avec les mêmes paramètres après son utilisation.

C'est ainsi que c'est fait en C++ dans les tests de QGIS https://github.com/qgis/QGIS/blob/master/tests/src/core/testqgsvectorlayercache.cpp#L191

2020-10-12 08:18 UTC, drillinP commented on veloroutes_voies_vertes/actions.py
> +    update_layer.commitChanges()
En effet

2020-10-12 10:27 UTC, drillinP commented on veloroutes_voies_vertes/actions.py
> +    update_layer.commitChanges()
J'ai testé est cela retourne une erreur comme quoi l'objet n'est pas connecté. Et en laissant comme j'avais fais pas d'erreur

2020-10-12 15:38 UTC, Gustry reviewed
It looks good

2020-10-12 15:38 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +from functools import partial
`functools` étant dans la librairie standard de Python, on place son import avant celui de `qgis.core` avec une ligne entre

2020-10-12 15:38 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +    print(layer_id)
Enlever les `print`

2020-10-12 15:38 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +                    'Véloroutes',
```suggestion
            'Véloroutes',
```
On garde le minimum d'indentation possible

2020-10-12 15:38 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +        'Création de l\'itinéraire Validée')
```suggestion
        'Création de l\'itinéraire validée')
```

2020-10-12 15:38 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +        'Véloroutes', str(new_feature['numero']))
Un message plus descriptif ou alors le message de L261 suffit ?

2020-10-12 15:38 UTC, Gustry commented on veloroutes_voies_vertes/actions.py
> +    layer.commitChanges()
Besoin de triggerRepaint sur les couches?

2020-10-13 06:54 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    update_layer.disconnect()
```suggestion
    update_layer.committedFeaturesAdded.disconnect()
```
Pourquoi pas plutôt ça ?

2020-10-13 07:18 UTC, rldhont requested changes

2020-10-13 07:18 UTC, rldhont commented on veloroutes_voies_vertes/actions.py
> +    iface.messageBar().pushCritical('Véloroutes', 'La couche {} a bien été réactualisée'.format(
Est-ce vraiment Critique comme message ?

2020-10-13 07:40 UTC, rldhont approved these changes

2020-10-13 07:51 UTC, Gustry approved these changes

2020-10-13 07:53 UTC, merged