Update field and style
3liz/qgis-veloroutes_voies_vertes-plugin pull request #78
Opened 2020-10-15 09:52 UTC by drillinP

## Description

* Ticket : #75 
*

2020-10-16 07:36 UTC, Gustry commented on veloroutes_voies_vertes/processing/covadis/export_covadis.py
> +            createByDefault=False
Est-ce que tu peux mettre ca dans un autre PR ?
Ce n'est pas lié à ce PR et suite à une discussion avec @rldhont ce matin, on va partir sur https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/issues/54#issuecomment-709091332

2020-10-16 09:37 UTC, rldhont requested changes

2020-10-16 09:37 UTC, rldhont commented on veloroutes_voies_vertes/processing/covadis/export_covadis.py
> +            createByDefault=False
Peux-tu retirer ce chengement ?

2020-10-19 08:03 UTC, Gustry approved these changes
LGTM

2020-10-19 08:05 UTC, rldhont commented
Désolé j'ai un doute, il faut vérifier les données sources.

2020-10-19 08:18 UTC, rldhont requested changes

2020-10-19 08:18 UTC, rldhont commented on veloroutes_voies_vertes/install/sql/veloroutes/10_FUNCTION.sql
> +		CAST(annee_subv as integer),
```suggestion
		CAST (annee_subv as integer),
```

2020-10-19 08:18 UTC, rldhont commented on veloroutes_voies_vertes/install/sql/veloroutes/10_FUNCTION.sql
> +		CAST(annee_subv as integer),
```suggestion
		CAST (annee_subv as integer),
```

2020-10-19 08:18 UTC, rldhont commented on veloroutes_voies_vertes/install/sql/upgrade/upgrade_to_0.4.0.sql
> +		CAST(annee_subv as integer),
```suggestion
		CAST (annee_subv as integer),
```

2020-10-19 08:18 UTC, rldhont commented on veloroutes_voies_vertes/install/sql/upgrade/upgrade_to_0.4.0.sql
> +		CAST(annee_subv as integer),
```suggestion
		CAST (annee_subv as integer),
```

2020-10-19 08:18 UTC, rldhont commented on veloroutes_voies_vertes/processing/covadis/export_covadis.py
> +            createByDefault=False
Ces modifications ne doivent pas être dans ce commit

2020-10-19 08:18 UTC, rldhont commented on veloroutes_voies_vertes/processing/covadis/export_covadis.py
> +            False,
Ces modifications ne doivent pas être dans ce commit

2020-10-19 08:55 UTC, rldhont commented
@drillinP tu peux faire un `git rebase master -i` et supprimer le commit **Remove changes in export alg**

2020-10-19 08:56 UTC, drillinP commented
@rldhont Fait

2020-10-19 08:58 UTC, rldhont approved these changes

2020-10-19 09:08 UTC, merged